[[simulations]]
iterations = ???
simulation_type = { test_statistic = ??? } #The D-max-value...

#Uncomment exactly one of the following options: 

#Kolmogorov-Smirnov-Test: 
#[simulations.simulation.Kolmogorov_Smirnov_test] 
#samples = ???
#distribution = {type = "Normal", mean = ???, stdev = ???}

#Lilliefors-Test: 
[simulations.simulation.Lilliefors_test] 
samples = ???
generating_distribution = {type = "Normal", mean = ???, stdev = ???} 
distribution_to_compare = "Normal" 
